env:
  node: true
  es2021: true
extends:
  - "eslint:recommended"
  - "prettier"
plugins:
  - "import"
reportUnusedDisableDirectives: true
parserOptions:
  ecmaVersion: 2022

rules:
  # Require packages to be listed in package.json
  "import/no-extraneous-dependencies": error

  # Disallow mutable exports
  "import/no-mutable-exports": error

  # Disallow other module systems
  "import/no-amd": error

  # Code style
  "import/first": error
  "import/newline-after-import": error
  "import/no-duplicates": error
  "import/order":
    - error
    - groups:
        - [builtin, internal, external]
        - parent
        - [index, sibling]
      "newlines-between": always
      alphabetize:
        order: asc

overrides:
  - files:
      - "**/*.mjs"
      - "packages/build-angular/src/**/*.js"
      - "packages/snuggery/src/**/*.js"
      - "packages/snuggery/*.js"
    parserOptions:
      ecmaVersion: 2022
      sourceType: module
  - files: ["integration/__fixtures__/angular/**/*.ts"]
    rules:
      "import/no-extraneous-dependencies": "off"
  - files: ["**/*.ts"]
    plugins:
      - "@typescript-eslint"
    parser: "@typescript-eslint/parser"
    parserOptions:
      ecmaVersion: 2022
      sourceType: module
    extends:
      - "plugin:@typescript-eslint/recommended"
      - "plugin:import/typescript"
    rules:
      "@typescript-eslint/no-non-null-assertion": "off"
      "@typescript-eslint/ban-types":
        - error
        - types:
            object: false
      "@typescript-eslint/no-unused-vars":
        - error
        - ignoreRestSiblings: true

      # This rule blocks lazy loading code, which is counterproductive
      "@typescript-eslint/no-var-requires": off

      no-restricted-syntax:
        - error
        # Disallow the private keyword except on constructors
        # @see https://github.com/typescript-eslint/typescript-eslint/issues/1391
        - selector: ':matches(PropertyDefinition, MethodDefinition, TSParameterProperty):not([kind="constructor"])[accessibility="private"]'
          message: "Use #private instead"
        # Disallow syntax not supported in node 16
        - selector: "StaticBlock"
          message: "Static initializers are not supported in node 16"
