changesetIgnorePatterns:
  - "**/__tests__/**"

enableScripts: false

npmPublishAccess: public

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-snuggery.cjs
    spec: "@yarnpkg/plugin-snuggery"

preferDeferredVersions: true
