changesetIgnorePatterns:
  - "**/__tests__/**"

enableScripts: false

npmPublishAccess: public

packageExtensions:
  "@angular-eslint/builder@*":
    peerDependenciesMeta:
      "@angular/cli":
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-snuggery.cjs
    spec: "@yarnpkg/plugin-snuggery"

preferDeferredVersions: true

yarnPath: .yarn/releases/yarn-4.12.0.cjs
