export {
	ConvertibleWorkspaceDefinition,
	ProjectDefinition,
	ProjectDefinitionCollection,
	TargetDefinition,
	TargetDefinitionCollection,
	WorkspaceDefinition,
	WorkspaceHost,
	workspaceFilenames,
	readWorkspace,
	writeWorkspace,
	updateWorkspace,
	JsonObject,
	JsonPropertyName,
	JsonPropertyPath,
	JsonValue,
} from './workspace';
