on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

name: "Test"
jobs:
  build-unit:
    name: Build & Unit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@0c618ceb2e48275dc06e86901822fd966ce75ba2
        with:
          node-version: 20.x
          corepack: yarn
          cache: yarn

      - name: Install
        run: |
          yarn install --immutable

      - name: Type-Check
        run: |
          yarn tsc -b

      - name: Build
        run: |
          yarn sn build

      - name: "Run tests"
        run: |
          yarn sn test

      - name: 'Validate help statements (fix w/ "yarn update-help")'
        run: |
          yarn update-help validate

      - name: "Validate CLI dependencies"
        run: |
          yarn sn --validate-cli-dependencies

  integration:
    name: "Integration tests on node.js ${{matrix.node}} on ${{matrix.os}}"
    needs: build-unit
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node:
          - 18.x
          - 20.x
        include:
          # Test on future node LTS
          - os: ubuntu-latest
            node: 22.x

    steps:
      - uses: actions/checkout@v4
      - name: "Use Node.js ${{matrix.node}}"
        uses: actions/setup-node@0c618ceb2e48275dc06e86901822fd966ce75ba2
        with:
          node-version: ${{matrix.node}}
          corepack: yarn
          cache: yarn

      - name: Install
        run: |
          yarn install --immutable

      - name: "Run tests"
        run: |
          yarn sn test integration
